config/routes.rb
Rails.application.routes.draw do
  resources :issues
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
  # Allow "faking" an error by giving issue a title matching /error/
  validates_format_of :title, without: /error/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      format.html do
        if @issue.save
          redirect_to @issue, notice: 'Issue was successfully created.'
        else
          render :new
        end
      end

      format.json do
        raise 'Error - should not get into `format.json` block.'
      end
    end
  end

  # PATCH/PUT /issues/1
  def update
    if @issue.update(issue_params)
      redirect_to @issue, notice: 'Issue was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /issues/1
  def destroy
    @issue.destroy
    redirect_to issues_url, notice: 'Issue was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def issue_params
      params.require(:issue).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>(Enter 'error' as the title to force a form validation error.)</p>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AxiosFormProxyExample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= yield %>
  </body>
</html>